### ISSUE TITLE
filtros de búsqueda cliente js

### ISSUE THREAD

**Issue by kevin-Oz** [tpi135-2019/MantenimientoDatosTaller#38]
- [x] búsqueda por placa (reparaciones)

- [x] búsqueda diagnostico

- [x] reparaciones entre fechas

- [ ]  reparaciones por identificador(combo completo)

- [ ] diagnostico por placa

- [x] exponer findbyNombre de la entidad Modelo

**Comment by Dragonkiller69** [comment]
"exponer findbyNombre de la entidad Modelo" este ya esta men pero en el path: 
api/marca/{id}/modelos?modelo={nombre} solo te muestra los qestan bajo cierta marca, no todos los modelos

**Comment by Dragonkiller69** [comment]
esto es algo random xd

**Comment by kevin-Oz** [comment]
entonces falta findbynombrelike de la entidad marca xd
